services:
  db:
    image: postgres:14-alpine
    volumes:
      - gateway_postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5010:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  gateway_postgres_data:
